import os

def options(ctx):
    os.environ['CC'] = 'riscv32-esp-elf-gcc'
    os.environ['AR'] = 'riscv32-esp-elf-ar'
    ctx.load('compiler_c')

def configure(ctx):
    os.environ['CC'] = 'riscv32-esp-elf-gcc'
    os.environ['AR'] = 'riscv32-esp-elf-ar'
    ctx.load('compiler_c')
    ctx.find_program('riscv32-esp-elf-gcc', var='CC', mandatory=True)
    ctx.find_program('riscv32-esp-elf-ar', var='AR', mandatory=True)
    ctx.env.LINK_CC = ctx.env.CC
    print("Using CC:", ctx.env.CC)

def build(ctx):
    ctx(
        features='c cprogram',
        source=[
            'src/main.c',
            'src/drivers/gpio.c',
            'src/system/firmware_storage.c',
            'src/syscalls.c',
            'src/startup.c',
        ],
        includes=[
            'src',
            'src/drivers',
            'src/board',
            'src/system',
        ],
        target='bootloader.elf',
        linkflags=['-T', '../esp32c3-bootloader.ld','-nostartfiles'],  # Adjust path as needed
    )