// src/fw/kernel/esp32-c3/kernel_main.c
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "system/logging.h"

#ifdef PHASE_1
#include "version.h"  // Generated by wscript
#endif

#define TAG "PEBBLE_KERNEL"
#define KERNEL_MAIN_STACK_SIZE (4 * 1024)


// Phase 1: Just prove kernel boots

static void kernel_main(void *arg) {
    LOG_INFO("ESP32-C3 Bootloader Starting\n");
    
    #ifdef PHASE_1
    LOG_INFO("Version: %s", PEBBLE_ESP32_VERSION_STRING);
    LOG_INFO("Git: %s", PEBBLE_ESP32_GIT_COMMIT);
    LOG_INFO("Phase 1: Foundation Layer Active");
    #endif
    
    while(1) {
        LOG_DEBUG("Kernel heartbeat - Phase %d", PEBBLE_ESP32_BUILD_PHASE);
        vTaskDelay(5000 / portTICK_PERIOD_MS);
    }
}

// Entry point from your existing boot_main()
void pebble_os_start(void) {
    LOG_INFO("Starting Pebble OS Phase %d...", PEBBLE_ESP32_BUILD_PHASE);
    
    // Create kernel task
    xTaskCreate(kernel_main, "pebble_kernel", KERNEL_MAIN_STACK_SIZE, NULL, 5, NULL);
    
    LOG_INFO("Pebble kernel task created");
}